# Generated by Django 4.1.2 on 2022-12-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=250)),
                ("deskripsi", models.TextField()),
                ("harga", models.IntegerField()),
            ],
        ),
    ]
