# Generated by Django 4.1.2 on 2022-12-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tukarpoin", "0002_poin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Poin",
        ),
    ]
