# Generated by Django 4.1.2 on 2022-10-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_rename_date_time_comment_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achiever',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
