# Generated by Django 4.1.2 on 2022-10-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_achiever_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achiever',
            old_name='username',
            new_name='name',
        ),
    ]
