# Generated by Django 4.1.2 on 2022-10-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_alter_achiever_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achiever',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
