# Generated by Django 4.1.2 on 2022-10-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_alter_achiever_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achiever',
            name='username',
        ),
    ]
