<<<<<<< HEAD
# Generated by Django 4.1 on 2022-10-25 13:53
=======
# Generated by Django 4.1.2 on 2022-10-17 08:40
>>>>>>> f4b80d01b7acf9d448825e225467cb30f569dca9

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import django.utils.timezone
=======
>>>>>>> f4b80d01b7acf9d448825e225467cb30f569dca9


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="WasteDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mass", models.FloatField()),
                ("description", models.TextField()),
                ("date_time", models.DateField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
=======
            name='WasteDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField()),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('PLASTIK', 'Plastik'), ('KACA', 'Kaca / Beling'), ('KERTAS', 'Kertas / Kardus'), ('ETC', 'Organik & Lainnya')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> f4b80d01b7acf9d448825e225467cb30f569dca9
            ],
        ),
    ]
