# Generated by Django 4.1.2 on 2022-10-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banksampah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedeposit',
            name='type',
            field=models.CharField(choices=[('PLASTIK', 'Plastik'), ('KACA', 'Kaca / Beling'), ('KERTAS', 'Kertas / Kardus'), ('ETC', 'Organik & Lainnya')], default=('PLASTIK', 'Plastik'), max_length=32),
        ),
    ]
