# Generated by Django 4.1 on 2022-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banksampah", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
