# Generated by Django 4.1 on 2022-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banksampah", "0002_alter_news_description_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
