# Generated by Django 4.1.2 on 2022-10-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banksampah', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WasteDeposit',
        ),
    ]
