# Generated by Django 4.1 on 2022-11-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.CharField(default="", max_length=2000),
        ),
    ]
